"""
Workflow Builder - Builder untuk membuat workflow dari template/config.
Digunakan untuk auto-generate workflow dari data Excel/CSV.
"""

from typing import Dict, List, Any, Optional
from datetime import datetime

from backend.core.workflow_parser import Workflow, WorkflowStep
from backend.core.action_registry import ActionRegistry


class WorkflowBuilder:
    """Builder untuk membuat workflow dari template/data source."""

    def __init__(self):
        self._step_counter = 0

    def _next_step_id(self) -> str:
        self._step_counter += 1
        return f"step_{self._step_counter}"

    def build_from_excel_config(self, headers: List[str], config: Dict[str, Any]) -> Dict[str, Any]:
        """
        Build workflow dict dari Excel headers + config dialog.

        Args:
            headers: List nama kolom dari Excel
            config: Konfigurasi dari AutoGenerateDialog

        Returns:
            Dict workflow yang siap di-parse oleh WorkflowParser
        """
        workflow_data = {
            "id": f"workflow_auto_{datetime.now().strftime('%Y%m%d_%H%M%S')}",
            "name": config.get("workflow_name", "Auto Generated Workflow"),
            "version": "1.0",
            "url": config.get("start_url", ""),
            "steps": [],
            "monitoring": {
                "screenshot_on_error": True,
                "screenshot_on_step": False,
                "log_level": "INFO"
            },
            "created_at": datetime.now().isoformat(),
            "updated_at": datetime.now().isoformat(),
        }

        steps: List[Dict[str, Any]] = []

        # 1. Navigate step (jika ada URL)
        start_url = config.get("start_url", "").strip()
        if start_url:
            steps.append({
                "id": self._next_step_id(),
                "type": "navigate",
                "label": "Navigate to URL",
                "params": {
                    "url": start_url,
                },
                "on_error": "stop",
                "retry": {"max_retries": 3, "delay": 2000},
            })

        # 2. Loop data source
        loop_step = {
            "id": self._next_step_id(),
            "type": "loop",
            "label": "Loop Data",
            "params": {
                "loop_type": "data_source",
            },
            "on_error": "stop",
            "retry": {"max_retries": 0, "delay": 0},
            "steps": [],
        }

        # 3. Action steps di dalam loop
        field_mappings = config.get("field_mappings", {})
        for header in headers:
            field_config = field_mappings.get(header, {})
            action_type = field_config.get("action_type", "input_text")
            label = field_config.get("label", header)

            params = self._get_default_action_params(action_type, header)

            loop_step["steps"].append({
                "id": self._next_step_id(),
                "type": action_type,
                "label": label,
                "params": params,
                "on_error": "skip",
                "retry": {"max_retries": 2, "delay": 1000},
            })

        steps.append(loop_step)

        # 4. Submit step (jika ada selector)
        submit_selector = config.get("submit_selector", "").strip()
        if submit_selector:
            steps.append({
                "id": self._next_step_id(),
                "type": "click",
                "label": "Submit Form",
                "params": {
                    "selector": submit_selector,
                },
                "on_error": "stop",
                "retry": {"max_retries": 3, "delay": 2000},
            })

        workflow_data["steps"] = steps
        return workflow_data

    def _get_default_action_params(self, action_type: str, header: str) -> Dict[str, Any]:
        """Buat default params berdasarkan action type dan nama kolom, mengacu ke action_registry."""
        safe_header = header.strip() or "field"

        registry = ActionRegistry()
        action = registry.get(action_type)
        base_params = dict(action.default_params) if action else {}

        if action_type == "input_text":
            base_params.update({
                "selector": f"input[name='{safe_header}']",
                "value": f"{{{{data.{safe_header}}}}}",
                "clear_before": True,
            })
        elif action_type == "click":
            base_params.update({
                "selector": f"button[name='{safe_header}']",
            })
        elif action_type == "select":
            base_params.update({
                "selector": f"select[name='{safe_header}']",
                "select_value": f"{{{{data.{safe_header}}}}}",
            })
        elif action_type == "upload_file":
            base_params.update({
                "selector": f"input[type='file'][name='{safe_header}']",
                "file_path": f"{{{{data.{safe_header}}}}}",
            })
        else:
            base_params.setdefault("selector", f"[name='{safe_header}']")

        return base_params

    def parse_to_workflow(self, workflow_data: Dict[str, Any]) -> Optional[Workflow]:
        """
        Parse workflow dict ke objek Workflow.

        Args:
            workflow_data: Dict hasil build_from_excel_config atau sejenisnya

        Returns:
            Workflow object atau None jika gagal parse
        """
        try:
            from backend.core.workflow_parser import WorkflowParser
            parser = WorkflowParser()
            return parser.parse(workflow_data)
        except Exception as e:
            print(f"Failed to parse generated workflow: {e}")
            return None