"""
Auto Generate Dialog - Dialog untuk konfigurasi auto-generate workflow dari Excel.
"""

from PySide6.QtWidgets import (
    QDialog, QVBoxLayout, QHBoxLayout, QLabel, QLineEdit,
    QPushButton, QFormLayout, QComboBox, QGroupBox, QTableWidget,
    QTableWidgetItem, QHeaderView, QMessageBox, QCheckBox,
)
from PySide6.QtCore import Qt


class AutoGenerateDialog(QDialog):
    """Dialog konfigurasi auto-generate workflow."""

    def __init__(self, headers: list, parent=None):
        super().__init__(parent)
        self.headers = headers
        self.setWindowTitle("Auto Generate Workflow")
        self.setMinimumWidth(600)
        self.setMinimumHeight(400)
        self._init_ui()

    def _init_ui(self):
        layout = QVBoxLayout(self)
        layout.setContentsMargins(16, 16, 16, 16)
        layout.setSpacing(10)

        # Info
        info_label = QLabel(
            "Konfigurasikan cara membuat workflow otomatis dari data Excel.\n"
            "Setiap kolom Excel akan diubah menjadi action step di dalam loop data."
        )
        info_label.setWordWrap(True)
        info_label.setStyleSheet("color: #666; font-size: 11px;")
        layout.addWidget(info_label)

        # Basic config
        basic_group = QGroupBox("Basic Configuration")
        basic_form = QFormLayout(basic_group)
        basic_form.setContentsMargins(8, 10, 8, 8)
        basic_form.setSpacing(6)

        self.workflow_name_input = QLineEdit("Auto Generated Workflow")
        basic_form.addRow("Workflow Name:", self.workflow_name_input)

        self.start_url_input = QLineEdit()
        self.start_url_input.setPlaceholderText("https://example.com/form")
        basic_form.addRow("Start URL:", self.start_url_input)

        self.submit_selector_input = QLineEdit()
        self.submit_selector_input.setPlaceholderText("button[type='submit']")
        basic_form.addRow("Submit Selector:", self.submit_selector_input)

        layout.addWidget(basic_group)

        # Field mappings
        mapping_group = QGroupBox("Field Mappings")
        mapping_layout = QVBoxLayout(mapping_group)
        mapping_layout.setContentsMargins(8, 10, 8, 8)
        mapping_layout.setSpacing(4)

        mapping_info = QLabel("Pilih tipe action untuk setiap kolom Excel.")
        mapping_info.setStyleSheet("color: #666; font-size: 10px;")
        mapping_layout.addWidget(mapping_info)

        self.mapping_table = QTableWidget()
        self.mapping_table.setColumnCount(3)
        self.mapping_table.setHorizontalHeaderLabels(["Excel Column", "Action Type", "Label"])
        self.mapping_table.horizontalHeader().setStretchLastSection(True)
        self.mapping_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.Stretch)
        self.mapping_table.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeToContents)
        self.mapping_table.horizontalHeader().setSectionResizeMode(2, QHeaderView.Stretch)
        self.mapping_table.setSelectionBehavior(QTableWidget.SelectRows)
        self.mapping_table.setSelectionMode(QTableWidget.SingleSelection)
        self.mapping_table.setStyleSheet("""
            QTableWidget {
                background: #fafafa;
                border: 1px solid #e0e0e0;
                border-radius: 4px;
                font-size: 10px;
            }
            QHeaderView::section {
                background: #f5f5f5;
                padding: 4px;
                border: 1px solid #e0e0e0;
                font-weight: bold;
                font-size: 10px;
            }
        """)

        action_types = ["input_text", "click", "select", "upload_file"]
        self.mapping_table.setRowCount(len(self.headers))

        for row, header in enumerate(self.headers):
            # Column name
            col_item = QTableWidgetItem(header)
            col_item.setFlags(col_item.flags() ^ Qt.ItemIsEditable)
            self.mapping_table.setItem(row, 0, col_item)

            # Action type
            action_combo = QComboBox()
            action_combo.addItems(action_types)
            action_combo.setCurrentText("input_text")
            self.mapping_table.setCellWidget(row, 1, action_combo)

            # Label
            label_item = QTableWidgetItem(header.replace("_", " ").title())
            self.mapping_table.setItem(row, 2, label_item)

        mapping_layout.addWidget(self.mapping_table)
        layout.addWidget(mapping_group)

        # Buttons
        btn_layout = QHBoxLayout()
        btn_layout.addStretch()

        self.generate_btn = QPushButton("Generate Workflow")
        self.generate_btn.setStyleSheet("""
            QPushButton {
                background: #FF9800; color: white; border: none;
                border-radius: 4px; padding: 8px 16px; font-weight: bold; font-size: 11px;
            }
            QPushButton:hover { background: #F57C00; }
        """)
        self.generate_btn.clicked.connect(self._on_generate)
        btn_layout.addWidget(self.generate_btn)

        cancel_btn = QPushButton("Cancel")
        cancel_btn.setStyleSheet("""
            QPushButton {
                background: #e2e6ea; color: #333; border: 1px solid #ced4da;
                border-radius: 4px; padding: 8px 16px; font-size: 11px;
            }
            QPushButton:hover { background: #dae0e5; }
        """)
        cancel_btn.clicked.connect(self.reject)
        btn_layout.addWidget(cancel_btn)

        layout.addLayout(btn_layout)

    def _on_generate(self):
        """Validate before accepting."""
        workflow_name = self.workflow_name_input.text().strip()
        if not workflow_name:
            QMessageBox.warning(self, "Validation Error", "Workflow name tidak boleh kosong.")
            return
        self.accept()

    def get_config(self) -> dict:
        """Kembalikan konfigurasi generate workflow."""
        field_mappings = {}
        for row, header in enumerate(self.headers):
            action_combo = self.mapping_table.cellWidget(row, 1)
            label_item = self.mapping_table.item(row, 2)
            field_mappings[header] = {
                "action_type": action_combo.currentText() if action_combo else "input_text",
                "label": label_item.text() if label_item else header,
                "params": {},
            }

        return {
            "workflow_name": self.workflow_name_input.text().strip(),
            "start_url": self.start_url_input.text().strip(),
            "submit_selector": self.submit_selector_input.text().strip(),
            "field_mappings": field_mappings,
        }